### ISSUE TITLE
footnotes_field: Document node context limitation

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/footnotes#10]
The *footnotes_field* submodule exposes a block with the footnotes used in a node and can be placed in a Layout. That's a great feature in my opinion, it allows you for instance to place the footnotes of a text in the sidebar of a page.

I've tested *footnotes_field*, and it works fine. As @docwilmot points out in #9, the submodule has a required context of 'node', that is a Layout with a path like `node/%`. That's fine for me but using the submodule without having to use a separate Layout would be more easy for people. So my questions are:

- What's the reason for the node context limitation?
- Is it possible to provide the functionality without having to use a node context, and is it worth it?

If we can't or don't want to change the node context limitation, let's add it to the documentation.

**Comment by docwilmot** [comment]
I suppose the block only makes sense being displayed on a node page. Is there any other page or entity where it is likely to be used? If not then it *requires* a node, and it makes sense to require the node context so people dont wonder why it doesnt show up.

**Comment by olafgrabienski** [comment]
I see, thanks for your feedback! To answer your question, I don't know of other than node pages or node entities where I would place the footnotes block.

My question came up because on some Backdrop sites I don't use use a node context Layout at all. If I need a block which makes only sense for nodes on these sites, I just set a visibility condition for the block. This approach doesn't work always, e.g. not for node content field blocks, but I tend to forget that.

> If we can't or don't want to change the node context limitation, let's add it to the documentation.

So, let's **not** change the node context limitation but add it to the documentation. I'll change the title of the issue respectively.

**Comment by olafgrabienski** [comment]
I've documented the node context limitation in the README file:

> To use the Footnotes block, enable the submodule, check the permission Administer footnotes fields, and place the block in a Layout with a 'node' context, i.e. with a path like node/%.
