### ISSUE TITLE
footnotes_wysiwyg: Can't insert footnote

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/footnotes#15]
While there is still an issue with editing existing footnotes (see the notes of the PR #9 description), the WYSIWYG submodule should at least be able to insert Footnotes. On my testing site however, I'm not able to insert a footnote: The modal dialog opens but the "Save" button doesn't close it again. And when I close the dialog using the **x** icon , the footnote isn't saved.

(I'll test the issue again on a clean site and will eventually provide more information.)

**Comment by docwilmot** [comment]
Sorry, I deleted what I thought was a redundant piece of code, and things kept working normally, but seems the old JS was still just cached in my browser. 
PR to follow.

**Comment by olafgrabienski** [comment]
No problem, and thanks for the PR!
