### ISSUE TITLE
footnotes_views: init method needs public declaration

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/footnotes#23]
I see this type of error when adding the views fields:

`Declaration of footnotes_views_handler_field_body_content::init(&$view, $options) should be compatible with views_handler_field_entity::init(&$view, &$options)`

Simple fix is to add `public` to `function init()` like:

```
public function init(&$view, &$options) {
```

**Comment by olafgrabienski** [comment]
Thanks for reporting! I've seen a bunch of other notices (cf. issue #13) but not this one, may have overseen it. Re the mentioned fix, there seem to be two files with the same line:

(a) footnotes_views_handler_field_body_content.inc, l. 13:
`function init(&$view, $options) {`

(b) footnotes_views_handler_field_body_footnotes.inc, l. 10:
`function init(&$view, $options) {`

I guess both have to be changed.

**Comment by herbdool** [comment]
Yes add the public to each.

**Comment by olafgrabienski** [comment]
@herbdool I've made a pull request, do you want to review or test it, or should I merge it right away?
