### ISSUE TITLE
Add LICENSE.txt

### ISSUE THREAD

**Issue by olafgrabienski** [backdrop-contrib/footnotes#27]
From the README.md:

> This project is GPL v2 software. See the LICENSE.txt file in this directory for complete text.

License file is missing so far, will add it.

**Comment by kndarp** [comment]
Hi! I'd like to help

**Comment by olafgrabienski** [comment]
Hey, very kind of you! How come your interest in Footnotes?

(Will have a look at the PR later.)

**Comment by kndarp** [comment]
I just started contributing to open source and learn from the community. 😃

**Comment by klonos** [comment]
@kndarp thanks for contributing. Any chance you can finish off https://github.com/olafgrabienski/footnotes/pull/29 as per @olafgrabienski's comments there?

**Comment by kndarp** [comment]
@klonos I've already made the suggested changes to the PR. Thanks

**Comment by olafgrabienski** [comment]
@kndarp Have you seen my other comment at https://github.com/olafgrabienski/footnotes/pull/29#pullrequestreview-169069335? Somehow a part of the file content seem to have gone lost, so I made another change request.
