### ISSUE TITLE
PHP 8.0 - Deprecated: Optional parameter $text declared before required parameter $format is implicitly treated as a required parameter

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/footnotes#35]
**Steps to reproduce**

1. Start with site using PHP 8.0 or greater
2. Download footnotes
3. Enable footnotes

**Expected results**
No errors 

**Actual results**
When enabled with `bee` I got the following error:

>  📝  Deprecated function: Optional parameter $text declared before required parameter $format is implicitly treated as a required parameter in include_once() (line 1521 of /app/docroot/core/includes/bootstrap.inc).

At the top of every page, got this:

> Deprecated: Optional parameter $text declared before required parameter $format is implicitly treated as a required parameter in /app/docroot/modules/contrib/footnotes/footnotes.module on line 63

**Comment by olafgrabienski** [comment]
@yorkshire-pudding Thanks for the report and the PR! I don't use `bee`, so I've tried to reproduce the issue without it:

1. Start with a site using PHP 8.1 (version `8.1.29` in my case)
2. Install Footnotes using the Project browser
3. Enable the (main) module in the module list

As a result, I didn't see any error. Is your issue related to how `bee` works, or are there other specific things on your site?

**Comment by olafgrabienski** [comment]
Oh, first I forgot to enable "Deprecated" on `admin/config/development/logging`. After enabling this category, I see two messages on _some_ pages:

- The function expanding_formatter_field_formatter_view() (expanding_formatter.module:320) called deprecated function filter_list_format(). It will be removed in the next major release of Backdrop.
- The function expanding_formatter_text_summary() (expanding_formatter.module:416) called deprecated function filter_list_format(). It will be removed in the next major release of Backdrop.

Do you see those as well? (I still don't see the messages mentioned in the issue description.)

**Comment by yorkshire-pudding** [comment]
@olafgrabienski 
It's odd. I can't get it when enabling or uninstalling in the UI, but I do get it when enabling AND uninstalling with bee. Bee uses standard Backdrop functions to `enable`, `disable` and `uninstall` and as it is a widely used tool with Backdrop, I think this should be fixed.  

Declaring required parameters after optional parameters has been deprecated since 8.0:
https://php.watch/versions/8.0/deprecate-required-param-after-optional

The other messages you are seeing belong to another module: `expanding_formatter`

**Comment by olafgrabienski** [comment]
Thanks for your feedback, @yorkshire-pudding, really odd! I'm still a bit cautious because of the differences between `bee` and the Backdrop Project Browser, but I'm definitely interested to fix the issue. I've had a look at the Drupal 7 queue and found an [issue which looks related](https://www.drupal.org/project/footnotes/issues/3312141). The [RTBC patch](https://www.drupal.org/project/footnotes/issues/3312141#comment-14709595) for that issue changes the same line as your PR does but in a different way. What do you think: is that issue related, and if so, which fix is preferable?

**Comment by yorkshire-pudding** [comment]
@olafgrabienski - this is almost identical. All mine does is add defensive coding but I'm happy to drop it.

**Comment by olafgrabienski** [comment]
I've merged the PR. By @yorkshire-pudding, thank you!
