### ISSUE TITLE
Organize the files

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/footnotes#8]
Hi Olaf, great work on this! I would recommend moving the files around so they're better organized. Isee the D7 version also has this. It looks a bit confusing.

1. I would recommend a directory "modules" and place all sub modules in there in their respective folders.
2. Put tests into a folder called /tests.
3. Put css into a folder called css.

**Comment by olafgrabienski** [comment]
Good idea, @herbdool! I was also thinking about a better file organization. Working on a module for the first time, I'm not sure if I can just move the files around, or if I have to adapt some paths then. (I guess, the latter must at least be done when CSS files are referenced somewhere.)

**Comment by olafgrabienski** [comment]
>> Working on a module for the first time, I'm not sure if I can just move the files around, or if I have to adapt some paths then.

> I think you can safely move your submodules into a new modules directory without making any other changes, except to make sure that each info file correctly references the respective script and css files (if they exist) with scripts[] and stylesheets[all][] . You might also move footnotes_views files into their own directory I suppose. (@Graham-72 via Gitter)

Good to know! And agreed, will also move the `footnotes_views` files into an own directory.

**Comment by olafgrabienski** [comment]
@docwilmot made the file reorganization in his [Initial work and bug fixes PR](https://github.com/olafgrabienski/footnotes/pull/9).

Thanks a lot, also to @herbdool for the suggestion and @Graham-72 for helpful hints.
